name: build
on:
  push:
    branches:
      - main
      - build-deploy
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup ZDE
        uses: zoul0813/zeal-dev-environment/github/setup-zde@main

      - name: Initialize mounts
        run: |
          mkdir -p $ZDE_PATH/mnt/romdisk
          mkdir -p $ZDE_PATH/mnt/eeprom
          mkdir -p $ZDE_PATH/mnt/roms

      - name: Build coreutils
        run: |
          cd $ZDE_PATH/home/zeal-coreutils && zde cmake && zde romdisk add bin

      - name: Build with ZDE
        run: |
          zde cmake && zde romdisk add bin/zshell

      - name: Create eeprom.img
        run: |
          cp ${{ github.workspace }}/.deploy/eeprom/* $ZDE_PATH/mnt/eeprom/
          zde image eeprom 64 # custom eeprom image
          cp $ZDE_PATH/mnt/eeprom.img ${{ github.workspace }}/.deploy/eeprom.img

      - name: Build Kernel/Romdisk
        env:
          ZDE_USER_PATH: ${{ github.workspace }}/.deploy
        run: |
          zde kernel user
          cp $ZDE_PATH/home/Zeal-8-bit-OS/build/os_with_romdisk.img bin/default.img
          cp $ZDE_PATH/home/Zeal-8-bit-OS/build/os_with_romdisk.img .deploy/default.img

      - name: Deploy
        uses: ./.github/actions/deploy-pages

      # - name: Upload binaries
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: zshell-binaries
      #     path: |
      #       bin/zshell
      #       bin/default.img
